name: Find Latest Release

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  find_latest_releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Python script
        run: python3 scripts/get_latest_episodes.py

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/latest_episodes.json

          if ! git diff --cached --quiet; then
            git commit -m "chore: auto-update latest episodes [skip ci]"
            git push
          else
            echo "No changes detected. Skipping commit."
          fi